version: '3'

services:
  gg:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 7724:3030
    volumes:
      - /Users/dillon/git/DATAS:/data
      - .:/code/
      - /code/node_modules/
